INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (1, 'Calliergon stramineum (Brid.) Kindb.', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (2, 'Hypericum punctatum Lam.', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (3, 'Saxifraga flagellaris Willd. ex Sternb. ssp. setig', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (4, 'Salix ovalifolia Trautv. var. ovalifolia', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (5, 'Argemone squarrosa Greene ssp. squarrosa', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (6, 'Cistanthe parryi (A. Gray) Hershkovitz var. nevade', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (7, 'Cladina (Nyl.) Nyl.', 'armor', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (8, 'Geocarpon Mack.', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (9, 'Phacelia pulchella A. Gray', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (10, 'Acarospora oligospora (Nyl.) Arnold', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (11, 'Trillium undulatum Willd.', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (12, 'Phacelia crenulata Torr. ex S. Watson var. corruga', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (13, 'Achnatherum diegoense (Swallen) Barkworth', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (14, 'Cyanea salicina H. Lév.', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (15, 'Scutellaria altamaha Small', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (16, 'Columbiadoria G.L. Nesom', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (17, 'Clarkia biloba (Durand) A. Nelson & J.F. Macbr.', 'armor', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (18, 'Calliergon megalophyllum Mikut.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (19, 'Allophyllum gilioides (Benth.) A.D. Grant & V.E. G', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (20, 'Packera ionophylla (Greene) W.A. Weber & Á. Löve', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (21, 'Astragalus didymocarpus Hook. & Arn. var. didymoca', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (22, 'Castela erecta Turp.', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (23, 'Spiraea chamaedryfolia L.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (24, 'Anulocaulis eriosolenus (A. Gray) Standl.', 'weapon', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (25, 'Oenothera rosea L\'Hér. ex Aiton', 'weapon', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (26, 'Mirabilis laevis (Benth.) Curran var. laevis', 'armor', 'epic');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (27, 'Ipomoea pes-tigridis L.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (28, 'Boronia Sm.', 'weapon', 'epic');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (29, 'Licaria triandra (Sw.) Kosterm.', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (30, 'Salvia fruticosa Mill.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (31, 'Spathoglottis Blume', 'armor', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (32, 'Bouteloua dimorpha J.T. Columbus', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (33, 'Arnica unalaschcensis Less.', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (34, 'Pycnanthemum incanum (L.) Michx. var. puberulum (E', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (35, 'Lechea minor L.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (36, 'Poa glauca Vahl ssp. rupicola (Nash ex Rydb.) W.A.', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (37, 'Hierochloe occidentalis Buckley', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (38, 'Arundinaria appalachiana Triplett, Weakley, & L.G.', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (39, 'Poa chaixii Vill.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (40, 'Pyrus communis L.', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (41, 'Carpinus betulus L.', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (42, 'Phacelia strictiflora (Engelm. & A. Gray) A. Gray ', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (43, 'Balanites aegyptiacus (L.) Delile', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (44, 'Leptochloa digitata (R. Br.) Domin', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (45, 'Baptisia sphaerocarpa Nutt.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (46, 'Costus scaber Ruiz & Pav.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (47, 'Camissonia exilis (P.H. Raven) P.H. Raven', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (48, 'Rubus rydbergianus L.H. Bailey', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (49, 'Phacelia constancei N.D. Atwood', 'weapon', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (50, 'Botrychium alaskense W.H. Wagner & J.R. Grant', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (51, 'Stachytarpheta cayennensis (Rich.) Vahl', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (52, 'Buellia lepidastra (Tuck.) Tuck.', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (53, 'Betula L.', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (54, 'Cirsium turneri Warnock', 'armor', 'rare');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (55, 'Ficus benjamina L.', 'weapon', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (56, 'Orthotrichum laevigatum J.E. Zetterst.', 'weapon', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (57, 'Machaerina restioides (Sw.) Vahl', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (58, 'Celastrus L.', 'armor', 'uncommon');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (59, 'Aponogeton distachyos L. f.', 'armor', 'common');
INSERT INTO looterbuddy.Items (itemID, name, type, rarity) VALUES (60, 'Koeleria macrantha (Ledeb.) Schult.', 'weapon', 'common');
